module.exports = {
    "JCBH": "监测编号",
    "XZQDM": "行政区代码",
    "AREA": "面积(㎡)",
    "BSM": "标识码",
    "SSDS": "所属地市",
    "SSXS": "所属县市",
    "SSXZ": "所属乡镇",
    // "SSC": "所属村",
    "QSIMG": "前时相影像名",
    "HSIMG": "后时相影像名",
    "QSX": "前时相",
    "HSX": "后时相",
    "BHYY": "变化原因",
    "ZXD": "置信度",
    "JCPC": "监测批次",
    "BZ": "备注",
    "JCSJ": "监测时间",
    "QLX": "前类型",
    "HLX": "后类型",
    "SFCD": "是否重叠",
    "CDL": "重叠率",
    "CHMJ": "相交面积",
    "SHAPE_Leng": "几何周长",
    "SHAPE_Area": "几何面积"
}
